version: 0.0
os: linux
files:
  - source: /mi-repositorio/build/libs/
    destination: /opt/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: codedeploy-scripts/install_tomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy-scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy-scripts/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/start.sh
      timeout: 300
      runas: root
